import type { CurriculumGrade, Topic } from '@/types';

// ─── 중학교 1학년 ─────────────────────────────────────────────────────────────
const middle1Topics: Topic[] = [
  {
    id: 'm1-earth-01',
    gradeLevel: 'middle-1',
    domain: 'earth',
    unit: '지권의 변화',
    subUnit: '지각과 암석',
    concepts: ['지각의 구성 원소', '암석의 종류(화성암·퇴적암·변성암)', '암석의 풍화'],
    keywords: ['지각', '맨틀', '화성암', '퇴적암', '변성암', '풍화'],
    prerequisites: [],
  },
  {
    id: 'm1-earth-02',
    gradeLevel: 'middle-1',
    domain: 'earth',
    unit: '지권의 변화',
    subUnit: '광물',
    concepts: ['광물의 특성(색·조흔색·굳기·쪼개짐)', '조암광물의 종류', '광물 감별법'],
    keywords: ['광물', '조흔색', '굳기', '모스 굳기계', '조암광물'],
    prerequisites: ['m1-earth-01'],
  },
  {
    id: 'm1-earth-03',
    gradeLevel: 'middle-1',
    domain: 'earth',
    unit: '지권의 변화',
    subUnit: '지층과 화석',
    concepts: ['지층의 생성 원리', '지층 해석(수평층·역전층·부정합)', '화석의 생성과 활용'],
    keywords: ['지층', '수평층', '역전층', '부정합', '화석', '표준화석', '시상화석'],
    prerequisites: ['m1-earth-01'],
  },
  {
    id: 'm1-earth-04',
    gradeLevel: 'middle-1',
    domain: 'earth',
    unit: '지권의 변화',
    subUnit: '지각 변동',
    concepts: ['판 구조론', '판의 경계(수렴·발산·보존)', '지진과 화산 분포'],
    keywords: ['판 구조론', '대륙 이동설', '해령', '해구', '지진', '화산'],
    prerequisites: ['m1-earth-01'],
  },
  {
    id: 'm1-phy-01',
    gradeLevel: 'middle-1',
    domain: 'physics',
    unit: '여러 가지 힘',
    subUnit: '중력과 탄성력',
    concepts: ['중력의 방향과 크기', '무게와 질량의 차이', '탄성력과 훅의 법칙'],
    keywords: ['중력', '무게', '질량', '탄성력', '훅의 법칙', '용수철상수'],
    prerequisites: [],
  },
  {
    id: 'm1-phy-02',
    gradeLevel: 'middle-1',
    domain: 'physics',
    unit: '여러 가지 힘',
    subUnit: '마찰력과 부력',
    concepts: ['마찰력의 종류(정지·운동)', '마찰력에 영향을 미치는 요인', '아르키메데스 원리', '부력의 계산'],
    keywords: ['정지마찰력', '운동마찰력', '부력', '아르키메데스 원리', '밀도'],
    prerequisites: ['m1-phy-01'],
  },
  {
    id: 'm1-bio-01',
    gradeLevel: 'middle-1',
    domain: 'biology',
    unit: '생물의 다양성',
    subUnit: '생물 분류',
    concepts: ['린네의 분류 체계(계·문·강·목·과·속·종)', '5계 분류', '학명 작성 규칙'],
    keywords: ['분류', '계', '종', '5계', '학명', '이명법'],
    prerequisites: [],
  },
  {
    id: 'm1-bio-02',
    gradeLevel: 'middle-1',
    domain: 'biology',
    unit: '생물의 다양성',
    subUnit: '동물과 식물의 특징',
    concepts: ['척추동물과 무척추동물', '관다발 식물과 비관다발 식물', '씨앗식물과 포자식물'],
    keywords: ['척추동물', '무척추동물', '관다발', '겉씨식물', '속씨식물'],
    prerequisites: ['m1-bio-01'],
  },
  {
    id: 'm1-chem-01',
    gradeLevel: 'middle-1',
    domain: 'chemistry',
    unit: '기체의 성질',
    subUnit: '입자 모형과 기체의 압력',
    concepts: ['물질의 입자성', '기체의 압력', '보일의 법칙(압력-부피 반비례)'],
    keywords: ['입자', '기체', '압력', '보일의 법칙', '기압'],
    prerequisites: [],
  },
  {
    id: 'm1-chem-02',
    gradeLevel: 'middle-1',
    domain: 'chemistry',
    unit: '기체의 성질',
    subUnit: '기체의 온도와 부피',
    concepts: ['샤를의 법칙(온도-부피 비례)', '절대온도', '기체 법칙의 일상 적용'],
    keywords: ['샤를의 법칙', '절대온도', '켈빈', '열팽창'],
    prerequisites: ['m1-chem-01'],
  },
  {
    id: 'm1-chem-03',
    gradeLevel: 'middle-1',
    domain: 'chemistry',
    unit: '물질의 상태 변화',
    subUnit: '상태 변화와 에너지',
    concepts: ['물질의 3가지 상태', '상태 변화의 종류(융해·기화·승화 등)', '잠열'],
    keywords: ['고체', '액체', '기체', '융해', '기화', '응고', '액화', '승화', '잠열'],
    prerequisites: [],
  },
  {
    id: 'm1-phy-03',
    gradeLevel: 'middle-1',
    domain: 'physics',
    unit: '빛과 파동',
    subUnit: '빛의 반사와 굴절',
    concepts: ['빛의 반사 법칙', '거울의 종류와 상', '빛의 굴절과 스넬의 법칙', '렌즈의 종류와 상'],
    keywords: ['반사', '굴절', '스넬의 법칙', '전반사', '볼록렌즈', '오목렌즈'],
    prerequisites: [],
  },
];

// ─── 중학교 2학년 ─────────────────────────────────────────────────────────────
const middle2Topics: Topic[] = [
  {
    id: 'm2-chem-01',
    gradeLevel: 'middle-2',
    domain: 'chemistry',
    unit: '물질의 구성',
    subUnit: '원소와 원자',
    concepts: ['원소의 개념', '원자의 구조(핵·전자)', '원소 기호와 주기율표 기초'],
    keywords: ['원소', '원자', '핵', '양성자', '중성자', '전자', '원자번호'],
    prerequisites: [],
  },
  {
    id: 'm2-chem-02',
    gradeLevel: 'middle-2',
    domain: 'chemistry',
    unit: '물질의 구성',
    subUnit: '분자와 이온',
    concepts: ['분자의 개념과 분자식', '이온의 생성(양이온·음이온)', '이온 결합과 이온 화합물'],
    keywords: ['분자', '분자식', '이온', '양이온', '음이온', '전해질', '이온 결합'],
    prerequisites: ['m2-chem-01'],
  },
  {
    id: 'm2-phy-01',
    gradeLevel: 'middle-2',
    domain: 'physics',
    unit: '전기와 자기',
    subUnit: '전류와 전압',
    concepts: ['전하와 전류', '전압의 개념', '저항', '옴의 법칙(V=IR)'],
    keywords: ['전류', '전압', '저항', '옴의 법칙', '전자', '도체', '부도체'],
    prerequisites: [],
  },
  {
    id: 'm2-phy-02',
    gradeLevel: 'middle-2',
    domain: 'physics',
    unit: '전기와 자기',
    subUnit: '전기 회로',
    concepts: ['직렬연결과 병렬연결', '전력과 전력량', '전기 에너지 계산'],
    keywords: ['직렬', '병렬', '합성저항', '전력', '전력량', 'kWh'],
    prerequisites: ['m2-phy-01'],
  },
  {
    id: 'm2-phy-03',
    gradeLevel: 'middle-2',
    domain: 'physics',
    unit: '전기와 자기',
    subUnit: '자기장',
    concepts: ['자기장의 방향', '전류에 의한 자기장', '전자기 유도', '발전기·전동기 원리'],
    keywords: ['자기장', '자기력선', '전자기 유도', '패러데이 법칙', '발전기', '전동기'],
    prerequisites: ['m2-phy-01'],
  },
  {
    id: 'm2-earth-01',
    gradeLevel: 'middle-2',
    domain: 'earth',
    unit: '태양계',
    subUnit: '지구와 달',
    concepts: ['지구의 자전과 공전', '달의 위상 변화', '일식과 월식'],
    keywords: ['자전', '공전', '달의 위상', '일식', '월식', '조석'],
    prerequisites: [],
  },
  {
    id: 'm2-earth-02',
    gradeLevel: 'middle-2',
    domain: 'earth',
    unit: '태양계',
    subUnit: '태양계 행성',
    concepts: ['태양계 구성원', '행성의 분류(지구형·목성형)', '케플러 법칙'],
    keywords: ['태양계', '행성', '지구형', '목성형', '소행성', '혜성', '케플러'],
    prerequisites: ['m2-earth-01'],
  },
  {
    id: 'm2-bio-01',
    gradeLevel: 'middle-2',
    domain: 'biology',
    unit: '식물과 에너지',
    subUnit: '광합성',
    concepts: ['광합성 반응식', '엽록소의 역할', '광합성에 영향을 미치는 요인'],
    keywords: ['광합성', '엽록소', '엽록체', '이산화탄소', '포도당', '산소'],
    prerequisites: [],
  },
  {
    id: 'm2-bio-02',
    gradeLevel: 'middle-2',
    domain: 'biology',
    unit: '동물과 에너지',
    subUnit: '소화·순환·호흡·배설',
    concepts: ['소화 기관과 소화 효소', '혈액의 성분과 순환 경로', '호흡 기관과 세포 호흡', '배설 기관'],
    keywords: ['소화', '효소', '혈액', '혈구', '심장', '폐', '신장', '배설'],
    prerequisites: ['m2-bio-01'],
  },
  {
    id: 'm2-phy-04',
    gradeLevel: 'middle-2',
    domain: 'physics',
    unit: '열과 우리 생활',
    subUnit: '열과 온도, 비열',
    concepts: ['열과 온도의 차이', '비열의 개념', '열팽창', '열의 이동 방식(전도·대류·복사)'],
    keywords: ['열', '온도', '비열', '열팽창', '전도', '대류', '복사', '열평형'],
    prerequisites: [],
  },
];

// ─── 중학교 3학년 ─────────────────────────────────────────────────────────────
const middle3Topics: Topic[] = [
  {
    id: 'm3-chem-01',
    gradeLevel: 'middle-3',
    domain: 'chemistry',
    unit: '화학 반응의 규칙성',
    subUnit: '물질의 변화와 화학 반응식',
    concepts: ['물리 변화와 화학 변화', '화학 반응식 작성법', '화학 반응식의 의미'],
    keywords: ['물리변화', '화학변화', '화학반응식', '계수', '원자수 보존'],
    prerequisites: ['m2-chem-01', 'm2-chem-02'],
  },
  {
    id: 'm3-chem-02',
    gradeLevel: 'middle-3',
    domain: 'chemistry',
    unit: '화학 반응의 규칙성',
    subUnit: '질량 보존·일정 성분비 법칙',
    concepts: ['질량 보존의 법칙', '일정 성분비의 법칙', '화합물에서 원소의 질량비'],
    keywords: ['질량보존', '라부아지에', '일정성분비', '프루스트'],
    prerequisites: ['m3-chem-01'],
  },
  {
    id: 'm3-earth-01',
    gradeLevel: 'middle-3',
    domain: 'earth',
    unit: '기권과 날씨',
    subUnit: '대기와 기압',
    concepts: ['기권의 층상 구조', '기압의 정의와 측정', '바람의 발생 원리'],
    keywords: ['대류권', '성층권', '기압', '풍향', '풍속', '고기압', '저기압'],
    prerequisites: [],
  },
  {
    id: 'm3-earth-02',
    gradeLevel: 'middle-3',
    domain: 'earth',
    unit: '기권과 날씨',
    subUnit: '날씨 변화',
    concepts: ['구름과 강수', '기단과 전선', '우리나라의 계절별 날씨'],
    keywords: ['기단', '전선', '온난전선', '한랭전선', '폐색전선', '장마'],
    prerequisites: ['m3-earth-01'],
  },
  {
    id: 'm3-phy-01',
    gradeLevel: 'middle-3',
    domain: 'physics',
    unit: '운동과 에너지',
    subUnit: '속력과 운동',
    concepts: ['속력과 속도', '등속 운동', '등가속도 운동', 'v-t 그래프 해석'],
    keywords: ['속력', '속도', '가속도', '등속운동', '등가속도', 'v-t그래프'],
    prerequisites: [],
  },
  {
    id: 'm3-phy-02',
    gradeLevel: 'middle-3',
    domain: 'physics',
    unit: '운동과 에너지',
    subUnit: '힘과 운동, 일·에너지',
    concepts: ['뉴턴 운동 법칙(관성·가속도·작용반작용)', '일의 정의(W=Fs)', '운동 에너지와 위치 에너지', '역학적 에너지 보존'],
    keywords: ['관성', '뉴턴 2법칙', 'F=ma', '일', '운동에너지', '위치에너지', '역학적에너지보존'],
    prerequisites: ['m3-phy-01'],
  },
  {
    id: 'm3-bio-01',
    gradeLevel: 'middle-3',
    domain: 'biology',
    unit: '자극과 반응',
    subUnit: '감각기관과 신경계',
    concepts: ['감각 기관의 구조와 기능', '뉴런의 구조와 흥분 전달', '중추신경계와 말초신경계'],
    keywords: ['뉴런', '시냅스', '반사', '중추신경계', '말초신경계', '흥분'],
    prerequisites: [],
  },
  {
    id: 'm3-bio-02',
    gradeLevel: 'middle-3',
    domain: 'biology',
    unit: '생식과 유전',
    subUnit: '세포 분열과 유전',
    concepts: ['체세포 분열(유사분열)', '감수 분열', '멘델의 유전 법칙', '유전자형과 표현형'],
    keywords: ['체세포분열', '감수분열', '멘델', '우성', '열성', '유전자형', '표현형'],
    prerequisites: ['m3-bio-01'],
  },
  {
    id: 'm3-phy-03',
    gradeLevel: 'middle-3',
    domain: 'physics',
    unit: '에너지 전환과 보존',
    subUnit: '에너지의 형태와 전환',
    concepts: ['에너지의 다양한 형태', '에너지 전환 사례', '에너지 보존 법칙'],
    keywords: ['에너지', '역학적', '열에너지', '전기에너지', '에너지보존', '열효율'],
    prerequisites: ['m3-phy-02'],
  },
  {
    id: 'm3-earth-03',
    gradeLevel: 'middle-3',
    domain: 'earth',
    unit: '별과 우주',
    subUnit: '별의 거리와 특성',
    concepts: ['별의 밝기와 등급', '별의 색과 온도', '우리은하의 구조', '우주의 팽창'],
    keywords: ['등급', '광도', '시차', '파섹', '우리은하', '허블법칙'],
    prerequisites: [],
  },
];

// ─── 고등학교 통합과학 ──────────────────────────────────────────────────────────
const highIntegratedTopics: Topic[] = [
  {
    id: 'hi-01',
    gradeLevel: 'high-integrated',
    domain: 'integrated',
    unit: '물질과 규칙성',
    subUnit: '우주의 시작과 원소의 생성',
    concepts: ['빅뱅 우주론', '수소·헬륨의 생성', '별의 핵융합과 무거운 원소 생성'],
    keywords: ['빅뱅', '핵합성', '별의 진화', '초신성'],
    prerequisites: [],
  },
  {
    id: 'hi-02',
    gradeLevel: 'high-integrated',
    domain: 'integrated',
    unit: '물질과 규칙성',
    subUnit: '원소의 주기성과 화학 결합',
    concepts: ['주기율표의 주기성', '이온 결합과 공유 결합', '결합의 성질과 물질의 특성'],
    keywords: ['주기율표', '금속성', '비금속성', '이온결합', '공유결합', '전기음성도'],
    prerequisites: ['m2-chem-01', 'm2-chem-02'],
  },
  {
    id: 'hi-03',
    gradeLevel: 'high-integrated',
    domain: 'integrated',
    unit: '시스템과 상호작용',
    subUnit: '역학적 시스템',
    concepts: ['중력과 역학적 에너지', '운동량 보존', '충격량'],
    keywords: ['중력', '운동량', '충격량', '역학적에너지보존'],
    prerequisites: ['m3-phy-02'],
  },
  {
    id: 'hi-04',
    gradeLevel: 'high-integrated',
    domain: 'integrated',
    unit: '시스템과 상호작용',
    subUnit: '지구 시스템과 생명 시스템',
    concepts: ['지권·기권·수권·생물권의 상호작용', '세포의 구조와 기능', '세포막을 통한 물질 이동'],
    keywords: ['지구시스템', '탄소순환', '세포', '세포막', '삼투', '확산'],
    prerequisites: [],
  },
  {
    id: 'hi-05',
    gradeLevel: 'high-integrated',
    domain: 'integrated',
    unit: '변화와 다양성',
    subUnit: '화학 변화(산화-환원, 산-염기)',
    concepts: ['산화·환원 반응', '산화수', '산과 염기', 'pH와 중화 반응'],
    keywords: ['산화', '환원', '산화수', '산', '염기', 'pH', '중화반응'],
    prerequisites: ['m3-chem-01', 'm3-chem-02'],
  },
  {
    id: 'hi-06',
    gradeLevel: 'high-integrated',
    domain: 'integrated',
    unit: '변화와 다양성',
    subUnit: '생물 다양성과 진화',
    concepts: ['다윈의 자연선택설', '변이와 유전자 돌연변이', '진화와 생물다양성'],
    keywords: ['진화', '자연선택', '변이', '돌연변이', '적응'],
    prerequisites: ['m3-bio-02'],
  },
  {
    id: 'hi-07',
    gradeLevel: 'high-integrated',
    domain: 'integrated',
    unit: '환경과 에너지',
    subUnit: '생태계와 에너지 흐름',
    concepts: ['먹이사슬과 먹이그물', '물질 순환과 에너지 흐름', '생태계 평형'],
    keywords: ['생산자', '소비자', '분해자', '에너지 피라미드', '탄소순환'],
    prerequisites: [],
  },
];

// ─── 고등학교 물리학 I ─────────────────────────────────────────────────────────
const highPhysics1Topics: Topic[] = [
  {
    id: 'hp1-01',
    gradeLevel: 'high-physics1',
    domain: 'physics',
    unit: '역학과 에너지',
    subUnit: '등가속도 운동과 힘',
    concepts: ['등가속도 운동 방정식', '뉴턴 법칙의 응용', '마찰력·장력을 포함한 연립 방정식'],
    keywords: ['등가속도', 'v=v₀+at', 's=v₀t+½at²', '알짜힘', '장력'],
    prerequisites: ['m3-phy-01', 'm3-phy-02'],
  },
  {
    id: 'hp1-02',
    gradeLevel: 'high-physics1',
    domain: 'physics',
    unit: '역학과 에너지',
    subUnit: '운동량·충격량, 역학적 에너지',
    concepts: ['운동량-충격량 정리', '운동량 보존', '탄성 충돌과 비탄성 충돌', '역학적 에너지 보존'],
    keywords: ['운동량', '충격량', '탄성충돌', '비탄성충돌', '에너지보존'],
    prerequisites: ['hp1-01'],
  },
  {
    id: 'hp1-03',
    gradeLevel: 'high-physics1',
    domain: 'physics',
    unit: '전기와 자기',
    subUnit: '전기장과 전기력',
    concepts: ['쿨롱의 법칙', '전기장의 정의', '전위와 전기 퍼텐셜 에너지'],
    keywords: ['쿨롱의법칙', '전기장', '전위', '전하', '전기력'],
    prerequisites: ['m2-phy-01'],
  },
  {
    id: 'hp1-04',
    gradeLevel: 'high-physics1',
    domain: 'physics',
    unit: '전기와 자기',
    subUnit: '자기장과 전자기 유도',
    concepts: ['자기장의 방향(오른손 법칙)', '로런츠 힘', '패러데이의 전자기 유도 법칙', '렌츠의 법칙'],
    keywords: ['자기장', '로런츠힘', '전자기유도', '패러데이', '렌츠의법칙'],
    prerequisites: ['m2-phy-03'],
  },
  {
    id: 'hp1-05',
    gradeLevel: 'high-physics1',
    domain: 'physics',
    unit: '파동과 정보통신',
    subUnit: '파동의 성질과 빛',
    concepts: ['파동의 요소(파장·진동수·속력)', '파동의 간섭과 회절', '전자기파 스펙트럼'],
    keywords: ['파장', '진동수', '파속', '중첩', '간섭', '회절', '전자기파'],
    prerequisites: ['m1-phy-03'],
  },
];

// ─── 고등학교 화학 I ───────────────────────────────────────────────────────────
const highChemistry1Topics: Topic[] = [
  {
    id: 'hc1-01',
    gradeLevel: 'high-chemistry1',
    domain: 'chemistry',
    unit: '화학의 첫걸음',
    subUnit: '몰과 화학식량',
    concepts: ['아보가드로수', '몰의 개념', '화학식량·분자량·몰질량', '몰 계산'],
    keywords: ['아보가드로', '몰(mol)', '몰질량', '화학식량', '기체의 몰부피'],
    prerequisites: ['m3-chem-01'],
  },
  {
    id: 'hc1-02',
    gradeLevel: 'high-chemistry1',
    domain: 'chemistry',
    unit: '원자의 세계',
    subUnit: '원자 구조와 전자 배치',
    concepts: ['보어 원자 모형', '오비탈과 전자 배치(Aufbau 원리)', '원소의 주기적 성질'],
    keywords: ['보어모형', '오비탈', 'Aufbau', '훈트의법칙', '파울리배타원리', '전자배치'],
    prerequisites: ['m2-chem-01', 'hi-02'],
  },
  {
    id: 'hc1-03',
    gradeLevel: 'high-chemistry1',
    domain: 'chemistry',
    unit: '화학 결합과 분자의 세계',
    subUnit: '이온·공유·금속 결합',
    concepts: ['이온 결합의 에너지', '공유 결합과 Lewis 구조', '극성과 무극성', '분자의 모양(VSEPR)'],
    keywords: ['Lewis구조', 'VSEPR', '극성', '무극성', '쌍극자모멘트'],
    prerequisites: ['hc1-02'],
  },
  {
    id: 'hc1-04',
    gradeLevel: 'high-chemistry1',
    domain: 'chemistry',
    unit: '역동적인 화학 반응',
    subUnit: '반응 엔탈피와 화학 평형',
    concepts: ['발열·흡열 반응', '헤스의 법칙', '화학 평형과 평형상수', '르 샤틀리에 원리'],
    keywords: ['엔탈피', '헤스법칙', '화학평형', '평형상수', '르샤틀리에'],
    prerequisites: ['hc1-01', 'hi-05'],
  },
];

// ─── 고등학교 생명과학 I ───────────────────────────────────────────────────────
const highBiology1Topics: Topic[] = [
  {
    id: 'hb1-01',
    gradeLevel: 'high-biology1',
    domain: 'biology',
    unit: '세포와 생명활동',
    subUnit: '세포의 구조와 기능',
    concepts: ['세포 소기관의 종류와 기능', '세포막의 구조(유동 모자이크 모델)', '세포 분열 주기'],
    keywords: ['미토콘드리아', '엽록체', '리보솜', '세포막', '세포주기'],
    prerequisites: ['m2-bio-01'],
  },
  {
    id: 'hb1-02',
    gradeLevel: 'high-biology1',
    domain: 'biology',
    unit: '항상성과 몸의 조절',
    subUnit: '신경·호르몬 조절',
    concepts: ['흥분의 발생과 전달', '신경전달물질', '호르몬의 종류와 작용', '항상성 유지 메커니즘'],
    keywords: ['활동전위', '시냅스', '신경전달물질', '호르몬', '음성피드백'],
    prerequisites: ['m3-bio-01'],
  },
  {
    id: 'hb1-03',
    gradeLevel: 'high-biology1',
    domain: 'biology',
    unit: '항상성과 몸의 조절',
    subUnit: '면역',
    concepts: ['비특이적 면역(선천면역)', '특이적 면역(적응면역)', '항원-항체 반응', '백신의 원리'],
    keywords: ['면역', '항원', '항체', 'B세포', 'T세포', '백신'],
    prerequisites: ['hb1-02'],
  },
  {
    id: 'hb1-04',
    gradeLevel: 'high-biology1',
    domain: 'biology',
    unit: '유전',
    subUnit: 'DNA와 유전 정보',
    concepts: ['DNA 구조와 복제', '전사와 번역', '유전자 발현 조절'],
    keywords: ['DNA', 'RNA', '전사', '번역', '코돈', '단백질합성'],
    prerequisites: ['m3-bio-02'],
  },
  {
    id: 'hb1-05',
    gradeLevel: 'high-biology1',
    domain: 'biology',
    unit: '유전',
    subUnit: '사람의 유전',
    concepts: ['상염색체 유전', '성염색체 유전(반성유전)', '유전자 연관과 교차'],
    keywords: ['ABO식혈액형', '반성유전', '연관', '교차', '유전자지도'],
    prerequisites: ['hb1-04'],
  },
];

// ─── 고등학교 지구과학 I ───────────────────────────────────────────────────────
const highEarth1Topics: Topic[] = [
  {
    id: 'he1-01',
    gradeLevel: 'high-earth1',
    domain: 'earth',
    unit: '고체 지구',
    subUnit: '지구의 내부 구조',
    concepts: ['지진파(P파·S파)로 알아낸 지구 내부', '지각·맨틀·외핵·내핵', '지자기'],
    keywords: ['P파', 'S파', '지진파', '지각', '맨틀', '외핵', '내핵', '지자기'],
    prerequisites: ['m1-earth-04'],
  },
  {
    id: 'he1-02',
    gradeLevel: 'high-earth1',
    domain: 'earth',
    unit: '고체 지구',
    subUnit: '판 구조론과 지각 변동',
    concepts: ['판 경계의 종류', '맨틀 대류와 열점', '변환단층', '조산운동'],
    keywords: ['수렴경계', '발산경계', '보존경계', '열점', '변환단층', '조산운동'],
    prerequisites: ['he1-01'],
  },
  {
    id: 'he1-03',
    gradeLevel: 'high-earth1',
    domain: 'earth',
    unit: '대기와 해양',
    subUnit: '대기 대순환과 해류',
    concepts: ['해들리 셀·페렐 셀·극 셀', '무역풍과 편서풍', '해류의 종류와 원인'],
    keywords: ['대기대순환', '해들리셀', '무역풍', '편서풍', '난류', '한류'],
    prerequisites: ['m3-earth-01'],
  },
  {
    id: 'he1-04',
    gradeLevel: 'high-earth1',
    domain: 'earth',
    unit: '대기와 해양',
    subUnit: '기후 변화',
    concepts: ['기후 변화의 자연적·인위적 원인', '지구온난화의 메커니즘', '기후 변화 대응'],
    keywords: ['온실효과', 'CO₂', '기후변화', '밀란코비치주기', '탄소중립'],
    prerequisites: ['he1-03'],
  },
  {
    id: 'he1-05',
    gradeLevel: 'high-earth1',
    domain: 'earth',
    unit: '우주',
    subUnit: '별의 진화와 우주',
    concepts: ['별의 H-R도', '별의 진화 경로(주계열→거성→백색왜성 등)', '우주의 팽창과 빅뱅'],
    keywords: ['H-R도', '주계열성', '적색거성', '초신성', '블랙홀', '허블상수'],
    prerequisites: ['m3-earth-03'],
  },
];

// ─── 전체 커리큘럼 조합 ────────────────────────────────────────────────────────
export const CURRICULUM: CurriculumGrade[] = [
  {
    gradeLevel: 'middle-1',
    schoolLevel: 'middle',
    label: '중학교 1학년',
    description: '자연현상의 기초 개념 탐구 – 힘, 물질의 상태, 생물 분류, 지각 변동',
    topics: middle1Topics,
  },
  {
    gradeLevel: 'middle-2',
    schoolLevel: 'middle',
    label: '중학교 2학년',
    description: '물질의 구성과 에너지 – 원자·이온, 전기·자기, 태양계, 생명 에너지',
    topics: middle2Topics,
  },
  {
    gradeLevel: 'middle-3',
    schoolLevel: 'middle',
    label: '중학교 3학년',
    description: '화학 반응 규칙, 운동과 에너지, 유전, 날씨와 우주',
    topics: middle3Topics,
  },
  {
    gradeLevel: 'high-integrated',
    schoolLevel: 'high',
    label: '고등학교 통합과학',
    description: '물리·화학·생물·지구과학 융합 – 우주, 물질, 생명, 환경',
    topics: highIntegratedTopics,
  },
  {
    gradeLevel: 'high-physics1',
    schoolLevel: 'high',
    label: '물리학 I',
    description: '역학, 전자기학, 파동 – 수능 물리학 핵심 개념',
    topics: highPhysics1Topics,
  },
  {
    gradeLevel: 'high-chemistry1',
    schoolLevel: 'high',
    label: '화학 I',
    description: '몰 계산, 원자 구조, 화학 결합, 화학 평형',
    topics: highChemistry1Topics,
  },
  {
    gradeLevel: 'high-biology1',
    schoolLevel: 'high',
    label: '생명과학 I',
    description: '세포, 신경·호르몬, 면역, DNA와 유전',
    topics: highBiology1Topics,
  },
  {
    gradeLevel: 'high-earth1',
    schoolLevel: 'high',
    label: '지구과학 I',
    description: '지구 내부, 판 구조론, 대기·해양 순환, 별과 우주',
    topics: highEarth1Topics,
  },
];

// 특정 gradeLevel의 커리큘럼 찾기
export function getCurriculumByGrade(gradeLevel: string): CurriculumGrade | undefined {
  return CURRICULUM.find((c) => c.gradeLevel === gradeLevel);
}

// 특정 topicId로 단원 찾기
export function getTopicById(topicId: string): Topic | undefined {
  for (const grade of CURRICULUM) {
    const topic = grade.topics.find((t) => t.id === topicId);
    if (topic) return topic;
  }
  return undefined;
}

// 전체 단원 목록 평탄화
export function getAllTopics(): Topic[] {
  return CURRICULUM.flatMap((c) => c.topics);
}
